2018-02-19 10:22:56,561 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:94]
2018-02-19 10:24:08,386 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:24:08,386 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:24:08,386 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:24:08,386 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:24:08,386 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:24:08,387 ERROR: message [in dummy_api.py:57]
Traceback (most recent call last):
  File "dummy_api.py", line 43, in notifyapiUtility
    print content["task_type"]
TypeError: string indices must be integers, not str
2018-02-19 10:24:08,387 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dummy_api.py", line 58, in notifyapiUtility
    raise Exception(e)
Exception: string indices must be integers, not str
2018-02-19 10:25:06,753 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:97]
2018-02-19 10:25:11,111 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:25:11,111 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:25:11,111 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:25:11,111 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:25:11,112 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:25:11,112 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-02-19 10:28:12,322 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:28:16,811 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:28:16,811 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:28:16,811 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:28:16,812 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:28:16,812 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:28:16,812 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:28:16,812 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1725, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
2018-02-19 10:28:41,614 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:28:45,936 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:28:45,936 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:28:45,936 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:28:45,936 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:28:45,936 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:28:45,937 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:29:43,363 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:29:48,359 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:29:48,359 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:29:48,361 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:29:48,361 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:29:48,361 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:29:48,361 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:29:51,955 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:29:51,955 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:29:51,955 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:29:51,955 INFO: HTTP USER AGENT: curl/7.47.0 [in dummy_api.py:29]
2018-02-19 10:29:51,955 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:29:51,955 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:47:32,137 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:47:32,137 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:47:32,137 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:47:32,137 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:47:32,137 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:47:32,138 ERROR: message [in dummy_api.py:67]
Traceback (most recent call last):
  File "dummy_api.py", line 40, in notifyapiUtility
    content = request.json #get_json(silent=True)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 108, in json
    return self.get_json()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 162, in get_json
    rv = self.on_json_loading_failed(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 182, in on_json_loading_failed
    raise BadRequest()
BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2018-02-19 10:47:32,141 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dummy_api.py", line 68, in notifyapiUtility
    raise Exception(e)
Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2018-02-19 10:48:59,108 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:49:05,603 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:49:05,603 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:49:05,603 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:49:05,603 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:49:05,603 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:49:05,603 ERROR: message [in dummy_api.py:67]
Traceback (most recent call last):
  File "dummy_api.py", line 40, in notifyapiUtility
    content = request.json #get_json(silent=True)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 108, in json
    return self.get_json()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 162, in get_json
    rv = self.on_json_loading_failed(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/wrappers.py", line 182, in on_json_loading_failed
    raise BadRequest()
BadRequest: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2018-02-19 10:49:05,604 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dummy_api.py", line 68, in notifyapiUtility
    raise Exception(e)
Exception: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2018-02-19 10:50:10,398 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:50:10,398 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:50:10,398 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:50:10,398 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:50:10,398 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:50:10,399 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:51:11,602 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:51:17,884 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:51:17,885 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:51:17,885 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:51:17,885 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:51:17,885 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:51:17,885 ERROR: message [in dummy_api.py:67]
Traceback (most recent call last):
  File "dummy_api.py", line 41, in notifyapiUtility
    content = json.loada(content)
AttributeError: 'module' object has no attribute 'loada'
2018-02-19 10:51:17,888 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dummy_api.py", line 68, in notifyapiUtility
    raise Exception(e)
Exception: 'module' object has no attribute 'loada'
2018-02-19 10:51:38,282 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:51:41,900 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:51:41,900 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:51:41,900 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:51:41,900 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:51:41,900 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:51:41,900 ERROR: message [in dummy_api.py:67]
Traceback (most recent call last):
  File "dummy_api.py", line 41, in notifyapiUtility
    content = json.loads(content)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
2018-02-19 10:51:41,903 ERROR: Exception on /notify [POST] [in /home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s1bfwd/miniconda2/envs/msank_env/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "dummy_api.py", line 68, in notifyapiUtility
    raise Exception(e)
Exception: expected string or buffer
2018-02-19 10:52:01,535 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:52:52,795 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:52:56,561 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:52:56,561 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:52:56,561 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:52:56,561 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:52:56,562 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:52:56,562 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:53:59,996 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:54:04,091 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:54:04,092 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:54:04,092 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:54:04,092 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:54:04,092 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:54:04,092 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:54:50,076 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:54:53,108 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:54:53,108 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:54:53,108 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:54:53,108 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:54:53,108 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:54:53,109 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:55:26,179 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 10:55:29,040 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:55:29,041 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:55:29,041 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:55:29,041 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:55:29,041 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:55:29,041 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 10:56:45,371 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 10:56:45,371 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 10:56:45,371 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 10:56:45,371 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 10:56:45,371 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 10:56:45,372 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 11:12:26,510 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 11:12:26,510 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 11:12:26,510 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 11:12:26,510 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 11:12:26,510 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 11:12:26,511 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 11:14:54,455 INFO: SERVER STARTED ON  127.0.0.1:5020 [in dummy_api.py:104]
2018-02-19 11:15:15,937 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 11:15:15,937 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 11:15:15,937 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 11:15:15,937 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 11:15:15,937 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 11:15:15,938 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 11:18:55,599 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 11:18:55,599 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 11:18:55,599 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 11:18:55,599 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 11:18:55,599 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 11:18:55,600 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 11:50:53,573 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 11:50:53,573 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 11:50:53,573 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 11:50:53,573 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 11:50:53,573 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 11:50:53,573 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
2018-02-19 12:26:07,109 INFO: +++++ REQUEST RECEIVED +++++ [in dummy_api.py:21]
2018-02-19 12:26:07,109 INFO: REQUEST METHOD: POST [in dummy_api.py:27]
2018-02-19 12:26:07,109 INFO: REQUEST API: /notify [in dummy_api.py:28]
2018-02-19 12:26:07,109 INFO: HTTP USER AGENT: python-requests/2.18.4 [in dummy_api.py:29]
2018-02-19 12:26:07,109 INFO: CLIENT ADDRESS: 127.0.0.1 [in dummy_api.py:30]
2018-02-19 12:26:07,110 INFO: ----- REQUEST SERVED ----- [in dummy_api.py:63]
